---
title: Welcome to the Joyful World of Mathematics
author: ''
email: team@dhimath.org
description: We offer physical and digital, interactive exhibits for museums, schools
  etc.
baseurl: ''
url: ''
defaults: []
plugins: []
