---
title: 'DhiMath :: Math Exhibition India'
author: ''
email: team@dhimath.org
description: We offer physical and digital, interactive exhibits for museums, schools
  etc.
baseurl: "/dhimath-web"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
